version: '3'

volumes:
  aws:

services:
  aws-cli:
    build:
      context: .
      dockerfile: ./aws/Dockerfile
    tty: true
    volumes:
      - aws:/root/.aws 

  terraform:
    image: hashicorp/terraform:1.2.6
    env_file:
      - .aws.env
    volumes:
      - ./terraform:/src
    working_dir: /src
    entrypoint: ["sh"]
    tty: true